### ISSUE TITLE
extension .heif?

### ISSUE THREAD

**Issue by MarcWeber** [brookmiles/windows-heic-thumbnails#1]
If I understand correctly .heic is container format also for videos. but .heif is for images only. Your driver dosen't show .heif?
Is there is a reason for it? .heic works fine.

**Comment by brookmiles** [comment]
Only that my iPhone gives me .heic files which are what I had to test with.

They appear to be the same format, so yeah supporting .heif as well should just be a matter of the DLL registering the additional extension.

**Comment by Masamune3210** [comment]
there is a difference. HEIC is a container format, it can contain HEIF, but it can also contain other things. Its not just a renamed file extension.

**Comment by brookmiles** [comment]
> there is a difference. HEIC is a container format, it can contain HEIF, but it can also contain other things. Its not just a renamed file extension.

Based on https://nokiatech.github.io/heif/technical.html HEIF is the container format, and HEIC (or the .heic extension) is used to refer to HEIF files which use HEVC encoding.

Since I'm using https://github.com/strukturag/libheif to open and decode the images, adding support for .heif should only be a matter of registering to handle the additional extension.

**Comment by supermimai** [comment]
@brookmiles so finally, reading the last comment, is it still pending ( to open the heif files )  ?

**Comment by brookmiles** [comment]
> @brookmiles so finally, reading the last comment, is it still pending ( to open the heif files ) ?

Indeed I never actually got around to doing this, yet.  Though I do have time now, I should be able to take a look at it.

**Comment by brookmiles** [comment]
support for .heif added in https://github.com/brookmiles/windows-heic-thumbnails/releases/tag/v0.1.1
