### ISSUE TITLE
RogeuKiller Anti-Malware detecs strange thing

### ISSUE THREAD

**Issue by shytec** [brookmiles/windows-heic-thumbnails#3]
Hi, i get this message? False or?

O101 - Clsid
Gevonden
(X64) {2c93d534-2a1f-40d2-a375-babc92996987}
HKEY_CLASSES_ROOT\CLSID\{2c93d534-2a1f-40d2-a375-babc92996987}

![bub heic - 2023-12-15 12 19 34](https://github.com/brookmiles/windows-heic-thumbnails/assets/39877279/dcb94f20-2a3f-49cc-86cd-62bda32bfb22)

Is it safe?

**Comment by brookmiles** [comment]
Not really sure how to answer that... I believe it's safe because I'm the one who wrote it. You should of course be careful in general when you download software from random people on the internet.

The code is provided if you want to inspect it, or compile it yourself.

**Comment by Masamune3210** [comment]
It's....suspicious because its setting up a COM registration?

AV manufacturers really need to get it together and stop calling literally anything under the sun malicious.

**Comment by tomatotownn** [comment]
> AV manufacturers really need to get it together and stop calling literally anything under the sun malicious.

False postitives are better than false negatives

**Comment by Masamune3210** [comment]
Not really, especially when you start venturing more and more into excessiveness, as it causes users to take any and all complaints from the AV suite as immediate and irrefutable signs of malware.

Believe it or not, you can have too much of a good thing.
