### ISSUE TITLE
Windows Test client for checking which thumbnails creator is used

### ISSUE THREAD

**Issue by supermimai** [brookmiles/windows-heic-thumbnails#6]
Hello

In case there are several libraries to read / write thumbnail ( the one from windows store for exemple ) , which one is used ? ( the latest installed  ? ) 
is there any windows client app to know what codec is used in that case ? 
I m doing research on modern file format support ( but I m not a developper myself ), and it's hard to find information.

thanks !

Fabrice

**Comment by brookmiles** [comment]
> In case there are several libraries to read / write thumbnail ( the one from windows store for exemple ) , which one is used ? ( the latest installed ? ) 

Most likely the most recent one installed.  It should be possible to check using the registry editor, though it involves some digging.

If you look under `HKEY_CURRENT_USER\Software\Classes\.heic\ShellEx` (or for any file extension), there may be an optional key named `{e357fccd-a995-4576-b01f-234630154e96}` which is the thumbnail handler.  Viewing the value of that key will tell you the ID of the handler. If the DLL from this project is registered, that ID will be `{2c93d534-2a1f-40d2-a375-babc92996987}`, if the ID is different or missing, then something else may be handling the thumbnails.

If you then look up that ID under `Software\Classes\CLSID` you can find the name, and the path to the handler DLL under the `InProcServer32` key.

**Comment by zhaidong211** [comment]
Hello, Windows 10 computer installed, did not show the thumbnail heic, what is the reason?
